---
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/vic/Mail/meviccuadme/INBOX
  usual: true
  archived: false
  sync_back: true
  id: 1
  labels:
  - meviccuadme
  - Inbox
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/vic/Mail/meviccuadme/Compras
  usual: true
  archived: false
  sync_back: true
  id: 2
  labels:
  - meviccuadme
  - Compras
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/vic/Mail/meviccuadme/Debian
  usual: true
  archived: false
  sync_back: true
  id: 3
  labels:
  - meviccuadme
  - Debian
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/vic/Mail/meviccuadme/Drafts
  usual: true
  archived: false
  sync_back: true
  id: 4
  labels:
  - meviccuadme
  - Drafts
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/vic/Mail/meviccuadme/Junk
  usual: true
  archived: false
  sync_back: true
  id: 5
  labels:
  - meviccuadme
  - Junk
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/vic/Mail/meviccuadme/Registros
  usual: true
  archived: false
  sync_back: true
  id: 6
  labels:
  - meviccuadme
  - Registros
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/vic/Mail/meviccuadme/Sent
  usual: true
  archived: false
  sync_back: true
  id: 7
  labels:
  - meviccuadme
  - Sent
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/vic/Mail/meviccuadme/Trash
  usual: true
  archived: false
  sync_back: true
  id: 8
  labels:
  - meviccuadme
  - Trash
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/vic/Mail/meviccuadme/Vault
  usual: true
  archived: false
  sync_back: true
  id: 9
  labels:
  - meviccuadme
  - Vault
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/vic/Mail/meviccuadme/Viajes
  usual: true
  archived: false
  sync_back: true
  id: 10
  labels:
  - meviccuadme
  - Viajes
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/vic/Mail/debian-devel
  usual: true
  archived: true
  sync_back: true
  id: 11
  labels:
  - debian-devel
